wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1681148548.344241
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.16
      5: 0.13.5
      8:
      - 1
      - 4
      - 5
